SPECTACULAR_SETTINGS = {
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
    "TITLE": "TEST Django Rest API",
    "DESCRIPTION": "TEST Django Rest API",
    "SCHEMA_PATH_PREFIX": "/api/v1",
}
