# Generated by Django 5.1.6 on 2025-04-08 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('body', models.TextField(blank=True, null=True, verbose_name='body')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Phone number')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner'), ('manager', 'Manager'), ('user', 'User')], default='user', max_length=255, verbose_name='Role')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff status')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User Model',
                'verbose_name_plural': 'User Models',
                'db_table': 'users',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StadiumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Price per hour')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=13, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13, verbose_name='Longitude')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('length', models.IntegerField(verbose_name='Length')),
                ('width', models.IntegerField(verbose_name='Width')),
                ('roof', models.BooleanField(default=False, verbose_name='Stadium roof')),
                ('washroom', models.IntegerField(default=0, verbose_name='')),
                ('fields', models.IntegerField(default=1, verbose_name='Number of fields')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_stadiums', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_stadiums', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Stadium',
                'verbose_name_plural': 'Stadiums',
                'db_table': 'stadiums',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StadiumMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10, verbose_name='Media Type')),
                ('file', models.FileField(upload_to='stadium_media/', verbose_name='Media File')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='app.stadiummodel', verbose_name='Stadium')),
            ],
            options={
                'verbose_name': 'Stadium Media',
                'verbose_name_plural': 'Stadium Medias',
                'db_table': 'stadium_medias',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('reserved_for', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Reserved for')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='app.stadiummodel')),
            ],
            options={
                'verbose_name': 'Reservation Model',
                'verbose_name_plural': 'Reservations Models',
                'db_table': 'reservations',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Rating Score')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app.stadiummodel', verbose_name='Stadium')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'db_table': 'ratings',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='app.notificationmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
                'db_table': 'user_notification',
            },
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='notifications', through='app.UserNotificationModel', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
