# Generated by Django 5.1.6 on 2025-04-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('title', models.CharField(choices=[('title_1', 'Home construction'), ('title_2', 'Building remodels'), ('title_3', 'Interior design'), ('title_4', 'Exterior design'), ('title_5', 'Renovation'), ('title_6', 'Safety Management')], max_length=255, verbose_name='Title')),
                ('descripiton', models.TextField(max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
                'db_table': 'about',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'applications',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone number')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Location latitude')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Location longitude')),
                ('projects', models.PositiveIntegerField(verbose_name='Number of projects')),
                ('staff', models.PositiveIntegerField(verbose_name='Number of employees')),
                ('work', models.PositiveIntegerField(verbose_name='Hours of work ')),
                ('countries', models.PositiveIntegerField(verbose_name='Countries')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
                'db_table': 'company',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('descripiton', models.TextField(max_length=255, verbose_name='Description')),
                ('picture', models.FileField(upload_to='news/')),
            ],
            options={
                'verbose_name': 'New',
                'verbose_name_plural': 'News',
                'db_table': 'news',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PictureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('picture', models.FileField(upload_to='pictures/')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
                'db_table': 'news_picture',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('descripiton', models.TextField(max_length=255, verbose_name='Description')),
                ('slide', models.FileField(upload_to='slides/')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
                'db_table': 'slides',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('picture', models.FileField(upload_to='team_pictures/', verbose_name='Picture')),
                ('role', models.CharField(max_length=255, verbose_name='Role')),
                ('about', models.TextField(verbose_name='About')),
            ],
            options={
                'verbose_name': 'Team member',
                'verbose_name_plural': 'Team members',
                'db_table': 'team_members',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='usernotificationmodel',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='ratingmodel',
            name='stadium',
        ),
        migrations.RemoveField(
            model_name='ratingmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reservationmodel',
            name='stadium',
        ),
        migrations.RemoveField(
            model_name='reservationmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stadiummedia',
            name='stadium',
        ),
        migrations.RemoveField(
            model_name='stadiummodel',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='stadiummodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='usernotificationmodel',
            name='user',
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('client', models.CharField(max_length=255, verbose_name='Client')),
                ('architect', models.CharField(max_length=255, verbose_name='Architect')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('size', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Size (SF)')),
                ('completed_at', models.DateField(verbose_name='Completed at')),
                ('about', models.TextField(verbose_name='About')),
                ('category', models.ManyToManyField(blank=True, to='app.projectcategorymodel', verbose_name='Category')),
                ('picture', models.ManyToManyField(blank=True, to='app.picturemodel', verbose_name='Picture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('descritpion', models.TextField(verbose_name='Description')),
                ('picture', models.ManyToManyField(blank=True, null=True, to='app.picturemodel', verbose_name='Picture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='NotificationModel',
        ),
        migrations.DeleteModel(
            name='RatingModel',
        ),
        migrations.DeleteModel(
            name='ReservationModel',
        ),
        migrations.DeleteModel(
            name='StadiumMedia',
        ),
        migrations.DeleteModel(
            name='StadiumModel',
        ),
        migrations.DeleteModel(
            name='UserNotificationModel',
        ),
    ]
