# Generated by Django 5.1.6 on 2025-04-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmodel',
            old_name='descripiton',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='newsmodel',
            old_name='descripiton',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='servicemodel',
            old_name='descritpion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='slidemodel',
            old_name='descripiton',
            new_name='description',
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='short_description',
            field=models.TextField(default='', verbose_name='Short description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companymodel',
            name='about_us_short_text',
            field=models.TextField(default='', verbose_name='About us short text'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='short_description',
            field=models.TextField(default='', verbose_name='Short description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='short_description',
            field=models.TextField(default='', verbose_name='Short description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='short_description',
            field=models.TextField(default='', verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='slidemodel',
            name='short_description',
            field=models.TextField(default='', verbose_name='Short description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='picture',
            field=models.ManyToManyField(blank=True, to='app.picturemodel', verbose_name='Picture'),
        ),
    ]
